services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unipost-streamlit
    ports:
      - "8555:8555"
    environment:
      - DJANGO_API_URL=${DJANGO_API_URL}
      - ELASTICSEARCH_URL=${ES_HOST}
      - ELASTICSEARCH_USERNAME=${ES_USER}
      - ELASTICSEARCH_PASSWORD=${ES_PASS}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_started
    volumes:
      - .:/app
    networks:
      - unipost-network

  redis:
    image: redis:7-alpine
    container_name: unipost-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - unipost-network
    command: redis-server --appendonly yes

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: unipost-redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - unipost-network

volumes:
  redis_data:

networks:
  unipost-network:
    driver: bridge