version: '3.8'

services:
  unipost-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unipost-streamlit
    ports:
      - "8501:8501"
    environment:
      - DJANGO_API_URL=${DJANGO_API_URL}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - redis
    volumes:
      - ./app:/app
    networks:
      - unipost-network

  redis:
    image: redis:7-alpine
    container_name: unipost-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - unipost-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: unipost-kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_URL}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    networks:
      - unipost-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: unipost-redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - unipost-network

volumes:
  redis_data:

networks:
  unipost-network:
    driver: bridge