services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unipost-streamlit
    restart: unless-stopped
    ports:
      - "8555:8555"
    environment:
      - DJANGO_API_URL=${DJANGO_API_URL}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_started
    volumes:
      - .:/app
    networks:
      - unipost-network

  redis:
    image: redis:7-alpine
    container_name: unipost-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - unipost-network
    command: redis-server --appendonly yes

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: unipost-redis-commander
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - unipost-network

  nginx:
    image: nginx:alpine
    container_name: unipost-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - unipost-network

volumes:
  redis_data:

networks:
  unipost-network:
    driver: bridge
