[theme]
# Tema moderno e profissional para UniPost AI
base = "light"
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#333333"
font = "sans serif"

[server]
# Configurações do servidor
headless = true
port = 8555
address = "0.0.0.0"

[browser]
# Configurações do navegador
gatherUsageStats = false
