[theme]
# Tema moderno e profissional para UniPost AI
base = "light"
primaryColor = "#1f77b4"          # Azul moderno e acessível
backgroundColor = "#ffffff"        # Fundo branco puro
secondaryBackgroundColor = "#f8f9fa"  # Cinza muito claro para cards e elementos
textColor = "#333333"             # Texto escuro para boa legibilidade
font = "sans serif"               # Fonte limpa e moderna

[server]
# Configurações do servidor
headless = true
port = 8555
address = "0.0.0.0"

[browser]
# Configurações do navegador
gatherUsageStats = false
